//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGA.Presentacion.CAJA {
    
    
    public partial class frmConsultaBilletaje {
        
        /// <summary>
        /// Head1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// lblOpcion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase lblOpcion;
        
        /// <summary>
        /// LabelBase8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase8;
        
        /// <summary>
        /// LabelBase1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase1;
        
        /// <summary>
        /// dtpFechaSis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.CalendarioBase dtpFechaSis;
        
        /// <summary>
        /// LabelBase2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase2;
        
        /// <summary>
        /// txtCodUsu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.TextBoxBase txtCodUsu;
        
        /// <summary>
        /// LabelBase3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase3;
        
        /// <summary>
        /// txtUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.TextBoxBase txtUsuario;
        
        /// <summary>
        /// LabelBase5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase5;
        
        /// <summary>
        /// txtNomUsu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.TextBoxBase txtNomUsu;
        
        /// <summary>
        /// LabelBase11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase11;
        
        /// <summary>
        /// dtpProceso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.CalendarioBase dtpProceso;
        
        /// <summary>
        /// LabelBase12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase12;
        
        /// <summary>
        /// cboColaborador control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.ComboBoxUsuario cboColaborador;
        
        /// <summary>
        /// BotonProcesar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.BotonProcesar BotonProcesar1;
        
        /// <summary>
        /// PanelBase1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.PanelBase PanelBase1;
        
        /// <summary>
        /// dtgMonedas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.GridViewBase dtgMonedas;
        
        /// <summary>
        /// PanelBase2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.PanelBase PanelBase2;
        
        /// <summary>
        /// dtgBilletes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.GridViewBase dtgBilletes;
        
        /// <summary>
        /// LabelBase13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase13;
        
        /// <summary>
        /// txtMonMoneda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.NumberBox txtMonMoneda;
        
        /// <summary>
        /// LabelBase14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase14;
        
        /// <summary>
        /// txtMonBillete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.NumberBox txtMonBillete;
        
        /// <summary>
        /// LabelBase15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.LabelBase LabelBase15;
        
        /// <summary>
        /// txtMonTotal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.NumberBox txtMonTotal;
        
        /// <summary>
        /// btnImprimir control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.BotonImprimir btnImprimir;
        
        /// <summary>
        /// btnCancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGA.Controles.BotonCancelar btnCancelar;
    }
}
